const data = {
  products: [
    {
      name: "ER Collets",
      slug: "er-collets",
      category: "Collets",
      image: "/images/p1.jpeg", // 679px × 829px
      price: 40,
      countInStock: 10,
      brand: "SS Industry",
      rating: 4.5,
      numReviews: 10,
      description: "high quality collets",
    },
    {
      name: "R8 Collets",
      slug: "r8-collets",
      category: "collets",
      image: "/images/p2.jpeg",
      price: 70,
      countInStock: 0,
      brand: "SS Industry",
      rating: 4.0,
      numReviews: 10,
      description: "high quality collets",
    },
    {
      name: "TG Collets",
      slug: "tg-collets",
      category: "Collets",
      image: "/images/p3.jpeg",
      price: 25,
      countInStock: 15,
      brand: "SS Industries",
      rating: 4.5,
      numReviews: 14,
      description: "high quality collets",
    },
    {
      name: "355 E Collets",
      slug: "355-e-collets",
      category: "Collets",
      image: "/images/p4.jpeg",
      price: 65,
      countInStock: 5,
      brand: "SS Industries",
      rating: 4.5,
      numReviews: 10,
      description: "high quality collets",
    },
    {
      name: "Drill Collets",
      slug: "drill-collets",
      category: "Collets",
      image: "/images/p5.jpg",
      price: 70,
      countInStock: 5,
      brand: "SS Industries",
      rating: 4.5,
      numReviews: 10,
      description: "high quality collets",
    },
    {
      name: "Tap Collets",
      slug: "tap-collets",
      category: "Collets",
      image: "/images/p6.jpeg",
      price: 99,
      countInStock: 5,
      brand: "SS Industries",
      rating: 4.5,
      numReviews: 10,
      description: "high quality collets",
    },
  ],
};
export default data;
